_wandb:
    value:
        cli_version: 0.23.1
        e:
            ypj7r6z0anmo3j9fwu7nrhs181qm7m3b:
                codePath: mlops\training\train_ner.py
                codePathLocal: mlops\training\train_ner.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "314571747328"
                        used: "125520244736"
                executable: C:\Users\ASUS\miniconda3\envs\mlops310\python.exe
                git:
                    commit: 6ab945f8cd0d16a2fa2e08cf29eeaa2f04b49c1b
                    remote: https://github.com/Rudra1x/clinical-doc-ai.git
                host: Symantec
                memory:
                    total: "7949656064"
                os: Windows-10-10.0.26100-SP0
                program: D:\QUANTUM COMPUTING\Industry Projects\Data Analysis and Data Science\clinical-doc-ai\mlops\training\train_ner.py
                python: CPython 3.10.19
                root: D:\QUANTUM COMPUTING\Industry Projects\Data Analysis and Data Science\clinical-doc-ai
                startedAt: "2026-01-08T11:21:38.517936Z"
                writerId: ypj7r6z0anmo3j9fwu7nrhs181qm7m3b
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 103
                - 105
            "3":
                - 13
            "4": 3.10.19
            "5": 0.23.1
            "6": 4.57.3
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
